"""Markdown report generator."""

from __future__ import annotations

from datetime import datetime

from logdoctor.models import ScanResult


def generate_markdown_report(result: ScanResult) -> str:
    """Generate a Markdown report from a ScanResult."""
    lines: list[str] = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines.append("# LogDoctor Report")
    lines.append("")
    lines.append(f"**Generated:** {now}")
    lines.append(f"**File:** `{result.file_path}`")
    lines.append(f"**Log type:** {result.log_type.value}")
    lines.append(f"**Total lines:** {result.total_lines:,}")
    lines.append(f"**Analysis duration:** {result.duration_ms:.0f}ms")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("|--------|------:|")
    lines.append(f"| Critical | {result.critical_count} |")
    lines.append(f"| Errors | {result.errors_count} |")
    lines.append(f"| Warnings | {result.warnings_count} |")
    lines.append(f"| Total events | {len(result.matched_events)} |")
    lines.append("")

    if result.top_patterns:
        lines.append("## Top Patterns")
        lines.append("")
        lines.append("| # | Rule | Severity | Count | Description |")
        lines.append("|---|------|----------|------:|-------------|")
        for i, pat in enumerate(result.top_patterns[:20], start=1):
            lines.append(
                f"| {i} | {pat.name} | {pat.severity.value} "
                f"| {pat.count} | {pat.description} |",
            )
        lines.append("")

    events_with_ts = [e for e in result.matched_events if e.timestamp]
    if events_with_ts:
        lines.append("## Timeline")
        lines.append("")
        events_with_ts.sort(
            key=lambda e: e.timestamp or datetime.min,
        )
        lines.append("| Time | Severity | Message |")
        lines.append("|------|----------|---------|")
        for event in events_with_ts[:50]:
            ts = (
                event.timestamp.strftime("%Y-%m-%d %H:%M:%S")
                if event.timestamp
                else "N/A"
            )
            lines.append(f"| {ts} | {event.severity.value} | {event.message[:100]} |")
        lines.append("")

    recs = [(p.name, p.recommendation) for p in result.top_patterns if p.recommendation]
    if recs:
        lines.append("## Recommendations")
        lines.append("")
        for name, rec in recs:
            lines.append(f"- **{name}:** {rec}")
        lines.append("")

    if result.top_patterns:
        lines.append("## Detected Patterns")
        lines.append("")
        for pat in result.top_patterns:
            entry = (
                f"- `{pat.pattern_id}` — {pat.name} "
                f"({pat.severity.value}, {pat.count} occurrences)"
            )
            lines.append(entry)
        lines.append("")

    lines.append("---")
    lines.append("*Generated by LogDoctor*")
    lines.append("")

    return "\n".join(lines)
